---
seed: 2024

dataset:
  validation_2023:
    root_dir: ./data/validation/2023/2023/
    csv_path: ./data/validation/2023/2023/GroundTruth/val_HIPS_HYBRIDS_2023_V2.3.csv
    date_metadata_csv_path: ./data/validation/2023/2023//GroundTruth/DateofCollection.xlsx
  test_2023:
    root_dir: ./data/test/2023/
    csv_path: ./data/test/2023/GroundTruth/test_HIPS_HYBRIDS_2023_V2.3.csv
    date_metadata_csv_path: ./data/test/2023/GroundTruth/DateofCollection.xlsx

model:
  - cnn_lstm:
      config_path: ./config/base.yaml
      weights_path: ./assets/cnn_lstm_weights/cnn_lstm_1.ckpt

  - cnn_lstm:
      config_path: ./config/base_2.yaml
      weights_path: ./assets/cnn_lstm_weights/cnn_lstm_2.ckpt

  - cnn_lstm:
      config_path: ./config/base_3.yaml
      weights_path: ./assets/cnn_lstm_weights/cnn_lstm_3.ckpt

  - cnn_lstm:
      config_path: ./config/base_4.yaml
      weights_path: ./assets/cnn_lstm_weights/cnn_lstm_4.ckpt

  - cnn_lstm:
      config_path: ./config/base_5.yaml
      weights_path: ./assets/cnn_lstm_weights/cnn_lstm_5.ckpt

input_size: 24
